version: "3.8"

networks:
  application:
    driver: bridge

services:
  webserver:
    networks:
      - application
    image: nginx:mainline-alpine3.18-slim
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8001:80

  app:
    networks:
      - application
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www

  db:
    networks:
      - application
    image: mysql:8.0.40
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    networks:
      - application
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=db
      - UPLOAD_LIMIT=300m
    ports:
      - 8071:80

volumes:
  db-data: