name: Run Laravel Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: motion
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, ctype, json, pdo, mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M
          
      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist
        
      - name: Copy .env
        run: cp .env.example .env
        
      - name: Update .env database settings
        run: |
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_PORT=.*/DB_PORT=3306/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=motion/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=root/' .env
          
      - name: Generate App Key
        run: php artisan key:generate
        
      - name: Set up database
        run: |
          php artisan migrate --force
          
      - name: Run Tests
        run: php artisan test
